In [1]:
import numpy as np

fname = 'test1.txt'
N = 101
ti = 0
tf = 1
tspan = np.linspace(ti, tf, num = N)
ny = 4
nz = 2
n_p = 4
y0 = np.ones((N, ny), dtype = np.float64)
z0 = np.zeros((N, nz), dtype = np.float64)
p0 = np.ones((n_p), dtype = np.float64)
with open(fname, 'w') as f:
    # write number of nodes
    f.write('{}\n'.format('nt:'))
    f.write('{}\n'.format(N))
    # write time span
    f.write('{}\n'.format('t:'))
    # np.savetxt(f, tspan, delimiter=' ')
    tspan.tofile(f, sep = ' ')
    f.write('\n')
    # write number of y variables
    f.write('{}\n'.format('ny:'))
    f.write('{}\n'.format(ny))
    # write y variables
    f.write('{}\n'.format('y:'))
    np.savetxt(f, y0, delimiter=' ')
    # write number of z variables
    f.write('{}\n'.format('nz:'))
    f.write('{}\n'.format(nz))
    # write z variables
    f.write('{}\n'.format('z:'))
    np.savetxt(f, z0, delimiter=' ')
    # write number of p variables
    f.write('{}\n'.format('np：'))
    f.write('{}\n'.format(n_p))
    # write p variables
    f.write('{}\n'.format('p：'))
    p0.tofile(f, sep = ' ')

In [45]:
import numpy as np

fname = 'test2.txt'
N = 101
ti = 0
tf = 99
tspan = np.linspace(ti, tf, num = N)
ny = 4
nz = 2
n_p = 4
# y0 = np.ones((N, ny), dtype = np.float64)
y0 = np.arange(N * ny).reshape(N, ny)
#z0 = np.zeros((N, nz), dtype = np.float64)
z0 = np.arange(N * nz).reshape(N, nz)
#p0 = np.ones((n_p), dtype = np.float64)
p0 = np.arange(n_p)
with open(fname, 'w') as f:
    # write number of time nodes and the time span
    f.write('{}\n{}\n{}\n'.format('nt:', N, 't:'))
    # tspan.tofile(f, sep = ' ')
    np.savetxt(f, tspan, delimiter=' ', newline=" ")
    # write number of y variables and the y variables
    f.write('\n{}\n{}\n{}\n'.format('ny:', ny, 'y:'))
    np.savetxt(f, y0, delimiter=' ')
    # write number of z variables and the z variables
    f.write('{}\n{}\n{}\n'.format('nz:', nz, 'z:'))
    np.savetxt(f, z0, delimiter=' ')
    # write number of p variables and the p variables
    f.write('{}\n{}\n{}\n'.format('np:', n_p, 'p:'))
    # p0.tofile(f, sep = ' ')
    np.savetxt(f, p0, delimiter=' ', newline=" ")

In [47]:
with open(fname, 'r') as f:
    # read the number of time nodes and the time span variable
    line = f.readline()
    line = f.readline()
    N = int(line)
    line = f.readline()
    line = f.readline()
    list_tspan = line.rstrip().split(' ')
    tspan = np.zeros(N, dtype = np.float64)
    for i in range(N):
        tspan[i] = float(list_tspan[i])
    # read the number of y variables and the y variables
    line = f.readline()
    line = f.readline()
    n_y = int(line)
    line = f.readline()
    y0 = np.zeros((N, n_y), dtype = np.float64)
    for i in range(N):
        line = f.readline()
        list_y0 = line.rstrip().split(' ')
        for j in range(n_y):
            y0[i, j] = float(list_y0[j])
    # read the number of y variables and the y variables
    line = f.readline()
    line = f.readline()
    n_z = int(line)
    line = f.readline()
    z0 = np.zeros((N, n_z), dtype = np.float64)
    for i in range(N):
        line = f.readline()
        list_z0 = line.rstrip().split(' ')
        for j in range(n_z):
            z0[i, j] = float(list_z0[j])
    # read the number of p variables and the p variables
    line = f.readline()
    line = f.readline()
    n_p = int(line)
    line = f.readline()
    line = f.readline()
    list_p0 = line.rstrip().split(' ')
    p0 = np.zeros(n_p, dtype = np.float64)
    for i in range(n_p):
        p0[i] = float(list_p0[i])
print(tspan)
print(y0)
print(z0)
print(p0)

[ 0.    0.99  1.98  2.97  3.96  4.95  5.94  6.93  7.92  8.91  9.9  10.89
 11.88 12.87 13.86 14.85 15.84 16.83 17.82 18.81 19.8  20.79 21.78 22.77
 23.76 24.75 25.74 26.73 27.72 28.71 29.7  30.69 31.68 32.67 33.66 34.65
 35.64 36.63 37.62 38.61 39.6  40.59 41.58 42.57 43.56 44.55 45.54 46.53
 47.52 48.51 49.5  50.49 51.48 52.47 53.46 54.45 55.44 56.43 57.42 58.41
 59.4  60.39 61.38 62.37 63.36 64.35 65.34 66.33 67.32 68.31 69.3  70.29
 71.28 72.27 73.26 74.25 75.24 76.23 77.22 78.21 79.2  80.19 81.18 82.17
 83.16 84.15 85.14 86.13 87.12 88.11 89.1  90.09 91.08 92.07 93.06 94.05
 95.04 96.03 97.02 98.01 99.  ]
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]
 [ 20.  21.  22.  23.]
 [ 24.  25.  26.  27.]
 [ 28.  29.  30.  31.]
 [ 32.  33.  34.  35.]
 [ 36.  37.  38.  39.]
 [ 40.  41.  42.  43.]
 [ 44.  45.  46.  47.]
 [ 48.  49.  50.  51.]
 [ 52.  53.  54.  55.]
 [ 56.  57.  58.  59.]
 [ 60.  61.  62.  63.]
 [ 64.  65.  66.

In [8]:
fname = 'test3.txt'
try:
    with open(fname) as f: 
        print(f.readline())
except:
    print('oops')

oops
